repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-illegal-windows-names
    -   id: check-merge-conflict
    -   id: detect-private-key
        exclude_types: ["markdown"]
    -   id: mixed-line-ending